import React, { useState } from 'react';
import { 
  Eye, 
  AlertTriangle, 
  CheckCircle, 
  XCircle, 
  Download, 
  Printer, 
  Share2,
  Calendar,
  Stethoscope,
  Shield,
  TrendingUp,
  Info
} from 'lucide-react';
import { Card, Button, Badge, Alert, Progress } from './ui';

interface AnalysisResult {
  stage: number;
  confidence: number;
  riskLevel: 'low' | 'moderate' | 'high';
  recommendations: string[];
  timestamp?: string;
  imageUrl?: string;
  stageName?: string;
  imageQuality?: {
    qualityScore: number;
    brightness: number;
    contrast: number;
  };
}

interface ResultsDisplayProps {
  result: AnalysisResult;
  onNewAnalysis: () => void;
}

export const ResultsDisplay: React.FC<ResultsDisplayProps> = ({ result, onNewAnalysis }) => {
  const [showDetailedInfo, setShowDetailedInfo] = useState(false);

  const getStageInfo = (stage: number) => {
    const stageData = {
      0: {
        title: 'No Diabetic Retinopathy',
        description: 'No signs of diabetic retinopathy detected',
        color: 'emerald',
        icon: CheckCircle,
        severity: 'Normal'
      },
      1: {
        title: 'Mild Nonproliferative DR',
        description: 'Mild changes in blood vessels detected',
        color: 'blue',
        icon: Info,
        severity: 'Mild'
      },
      2: {
        title: 'Moderate Nonproliferative DR',
        description: 'Moderate changes requiring monitoring',
        color: 'amber',
        icon: AlertTriangle,
        severity: 'Moderate'
      },
      3: {
        title: 'Severe Nonproliferative DR',
        description: 'Significant changes requiring attention',
        color: 'orange',
        icon: AlertTriangle,
        severity: 'Severe'
      },
      4: {
        title: 'Proliferative Diabetic Retinopathy',
        description: 'Advanced stage requiring immediate care',
        color: 'red',
        icon: XCircle,
        severity: 'Critical'
      }
    };

    return stageData[stage as keyof typeof stageData] || stageData[0];
  };

  const getRiskBadgeVariant = (risk: string) => {
    switch (risk) {
      case 'low': return 'success';
      case 'moderate': return 'warning';
      case 'high': return 'danger';
      default: return 'info';
    }
  };

  const stageInfo = getStageInfo(result.stage);
  const IconComponent = stageInfo.icon;

  const handleDownloadReport = () => {
    // Simulate PDF generation
    console.log('Generating PDF report...');
  };

  const handlePrintReport = () => {
    window.print();
  };

  const handleShareResult = () => {
    if (navigator.share) {
      navigator.share({
        title: 'OpthalmoAI Retinal Screening Result',
        text: `Diabetic Retinopathy Analysis: Stage ${result.stage} detected with ${Math.round(result.confidence * 100)}% confidence`,
      });
    }
  };

  return (
    <div className="space-y-6">
      {/* Medical Disclaimer */}
      <Alert variant="warning" className="bg-amber-50/80 backdrop-blur-sm border-amber-200/50">
        <div className="flex items-start space-x-3">
          <Stethoscope className="h-5 w-5 text-amber-600 flex-shrink-0 mt-0.5" />
          <div>
            <p className="font-medium text-amber-800 mb-1">Important Medical Notice</p>
            <p className="text-amber-700 text-sm">
              These results are generated by AI analysis and are intended to <strong>assist healthcare professionals only</strong>. 
              This is <strong>not a medical diagnosis</strong>. Please consult with an ophthalmologist for proper medical evaluation and treatment decisions.
            </p>
          </div>
        </div>
      </Alert>

      {/* Main Results Card */}
      <Card className="relative overflow-hidden" glow>
        <div className="flex items-start justify-between mb-6">
          <div>
            <h2 className="text-2xl font-bold text-slate-800 mb-2">
              AI Analysis Results
            </h2>
            <p className="text-slate-600">
              Generated on {new Date().toLocaleDateString('en-US', { 
                year: 'numeric', 
                month: 'long', 
                day: 'numeric',
                hour: '2-digit',
                minute: '2-digit'
              })}
            </p>
          </div>
          <Badge variant={getRiskBadgeVariant(result.riskLevel)} className="text-sm px-3 py-1">
            {result.riskLevel.toUpperCase()} RISK
          </Badge>
        </div>

        {/* Stage Information */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6">
          {/* Stage Details */}
          <div className={`p-6 rounded-2xl bg-gradient-to-br from-${stageInfo.color}-50 to-${stageInfo.color}-100 border border-${stageInfo.color}-200`}>
            <div className="flex items-center space-x-4 mb-4">
              <div className={`flex items-center justify-center w-12 h-12 bg-${stageInfo.color}-500 rounded-xl shadow-md`}>
                <IconComponent className="h-7 w-7 text-white" />
              </div>
              <div>
                <h3 className={`text-lg font-bold text-${stageInfo.color}-800`}>
                  Stage {result.stage}
                </h3>
                <p className={`text-${stageInfo.color}-600 font-medium`}>
                  {stageInfo.severity}
                </p>
              </div>
            </div>
            <h4 className={`font-semibold text-${stageInfo.color}-800 mb-2`}>
              {stageInfo.title}
            </h4>
            <p className={`text-${stageInfo.color}-700 text-sm`}>
              {stageInfo.description}
            </p>
          </div>

          {/* Confidence Score */}
          <div className="p-6 rounded-2xl bg-gradient-to-br from-blue-50 to-teal-100 border border-blue-200">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-lg font-bold text-blue-800">
                AI Confidence
              </h3>
              <TrendingUp className="h-6 w-6 text-blue-600" />
            </div>
            <div className="space-y-3">
              <div className="text-3xl font-bold text-blue-800">
                {Math.round(result.confidence * 100)}%
              </div>
              <Progress 
                value={result.confidence * 100} 
                className="h-2" 
              />
              <p className="text-blue-700 text-sm">
                Model confidence in the analysis result
              </p>
            </div>
          </div>
        </div>

        {/* Recommendations */}
        <div className="mb-6">
          <h3 className="text-lg font-semibold text-slate-800 mb-4 flex items-center">
            <Eye className="h-5 w-5 mr-2 text-teal-600" />
            Clinical Recommendations
          </h3>
          <div className="grid gap-3">
            {result.recommendations.map((recommendation, index) => (
              <div
                key={index}
                className="flex items-start space-x-3 p-4 bg-slate-50/80 backdrop-blur-sm rounded-xl border border-slate-200/50 hover:bg-slate-100/80 transition-colors"
              >
                <div className="flex-shrink-0 w-6 h-6 bg-teal-100 rounded-full flex items-center justify-center mt-0.5">
                  <span className="text-teal-600 font-semibold text-sm">{index + 1}</span>
                </div>
                <p className="text-slate-700 text-sm leading-relaxed">{recommendation}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Actions */}
        <div className="flex flex-wrap gap-3 pt-6 border-t border-slate-200/50">
          <Button onClick={handleDownloadReport} variant="primary">
            <Download className="h-4 w-4 mr-2" />
            Download Report
          </Button>
          <Button onClick={handlePrintReport} variant="outline">
            <Printer className="h-4 w-4 mr-2" />
            Print Results
          </Button>
          <Button onClick={handleShareResult} variant="outline">
            <Share2 className="h-4 w-4 mr-2" />
            Share
          </Button>
          <Button onClick={onNewAnalysis} variant="ghost">
            <Eye className="h-4 w-4 mr-2" />
            New Analysis
          </Button>
        </div>
      </Card>

      {/* Detailed Information */}
      <Card>
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-lg font-semibold text-slate-800">
            Understanding Your Results
          </h3>
          <Button
            variant="ghost"
            size="sm"
            onClick={() => setShowDetailedInfo(!showDetailedInfo)}
          >
            {showDetailedInfo ? 'Hide Details' : 'Show Details'}
          </Button>
        </div>

        {showDetailedInfo && (
          <div className="space-y-4 pt-4 border-t border-slate-200/50">
            <div>
              <h4 className="font-medium text-slate-800 mb-2">Diabetic Retinopathy Stages:</h4>
              <div className="grid gap-3 text-sm">
                <div className="flex items-center space-x-3">
                  <div className="w-3 h-3 bg-emerald-500 rounded-full"></div>
                  <span className="text-slate-700"><strong>Stage 0:</strong> No diabetic retinopathy</span>
                </div>
                <div className="flex items-center space-x-3">
                  <div className="w-3 h-3 bg-blue-500 rounded-full"></div>
                  <span className="text-slate-700"><strong>Stage 1:</strong> Mild nonproliferative diabetic retinopathy</span>
                </div>
                <div className="flex items-center space-x-3">
                  <div className="w-3 h-3 bg-amber-500 rounded-full"></div>
                  <span className="text-slate-700"><strong>Stage 2:</strong> Moderate nonproliferative diabetic retinopathy</span>
                </div>
                <div className="flex items-center space-x-3">
                  <div className="w-3 h-3 bg-orange-500 rounded-full"></div>
                  <span className="text-slate-700"><strong>Stage 3:</strong> Severe nonproliferative diabetic retinopathy</span>
                </div>
                <div className="flex items-center space-x-3">
                  <div className="w-3 h-3 bg-red-500 rounded-full"></div>
                  <span className="text-slate-700"><strong>Stage 4:</strong> Proliferative diabetic retinopathy</span>
                </div>
              </div>
            </div>

            <div className="pt-4 border-t border-slate-200/50">
              <div className="flex items-start space-x-3">
                <Shield className="h-5 w-5 text-teal-600 flex-shrink-0 mt-0.5" />
                <div>
                  <h4 className="font-medium text-slate-800 mb-1">Privacy & Security</h4>
                  <p className="text-slate-600 text-sm">
                    Your retinal images are processed securely and are automatically deleted after analysis. 
                    No personal medical data is stored permanently, ensuring HIPAA compliance and patient privacy.
                  </p>
                </div>
              </div>
            </div>
          </div>
        )}
      </Card>

      {/* Next Steps */}
      <Card className="bg-gradient-to-r from-teal-50 to-blue-50 border-teal-200/50">
        <div className="flex items-start space-x-4">
          <div className="flex items-center justify-center w-12 h-12 bg-teal-500 rounded-xl shadow-md flex-shrink-0">
            <Calendar className="h-6 w-6 text-white" />
          </div>
          <div>
            <h3 className="text-lg font-semibold text-teal-800 mb-2">
              Next Steps
            </h3>
            <p className="text-teal-700 text-sm mb-4">
              Based on your AI screening results, we recommend scheduling an appointment with an ophthalmologist 
              for professional evaluation and to discuss appropriate treatment options if needed.
            </p>
            <Button variant="secondary" size="sm">
              <Stethoscope className="h-4 w-4 mr-2" />
              Find Healthcare Providers
            </Button>
          </div>
        </div>
      </Card>
    </div>
  );
};