import React, { useState } from 'react';
import { 
  Eye, 
  AlertTriangle, 
  CheckCircle, 
  XCircle, 
  Download, 
  Printer, 
  Share2,
  Calendar,
  Stethoscope,
  Shield,
  TrendingUp,
  Info
} from 'lucide-react';
import { Card, Button, Badge, Alert, Progress } from './ui';

interface AnalysisResult {
  stage: number;
  confidence: number;
  riskLevel: 'low' | 'moderate' | 'high';
  recommendations: string[];
  timestamp?: string;
  imageUrl?: string;
  stageName?: string;
  imageQuality?: {
    qualityScore: number;
    brightness: number;
    contrast: number;
  };
}

interface ResultsDisplayProps {
  result: AnalysisResult;
  onNewAnalysis: () => void;
}

export const ResultsDisplay: React.FC<ResultsDisplayProps> = ({ result, onNewAnalysis }) => {
  const [showDetailedInfo, setShowDetailedInfo] = useState(false);

  const getStageInfo = (stage: number) => {
    const stageData = {
      0: {
        title: 'No Diabetic Retinopathy',
        description: 'No signs of diabetic retinopathy detected',
        color: 'emerald',
        icon: CheckCircle,
        severity: 'Normal'
      },
      1: {
        title: 'Mild Nonproliferative DR',
        description: 'Mild changes in blood vessels detected',
        color: 'blue',
        icon: Info,
        severity: 'Mild'
      },
      2: {
        title: 'Moderate Nonproliferative DR',
        description: 'Moderate changes requiring monitoring',
        color: 'amber',
        icon: AlertTriangle,
        severity: 'Moderate'
      },
      3: {
        title: 'Severe Nonproliferative DR',
        description: 'Significant changes requiring attention',
        color: 'orange',
        icon: AlertTriangle,
        severity: 'Severe'
      },
      4: {
        title: 'Proliferative Diabetic Retinopathy',
        description: 'Advanced stage requiring immediate care',
        color: 'red',
        icon: XCircle,
        severity: 'Critical'
      }
    };

    return stageData[stage as keyof typeof stageData] || stageData[0];
  };

  const getRiskBadgeVariant = (risk: string) => {
    switch (risk) {
      case 'low': return 'success';
      case 'moderate': return 'warning';
      case 'high': return 'danger';
      default: return 'info';
    }
  };

  const stageInfo = getStageInfo(result.stage);
  const IconComponent = stageInfo.icon;

  const handleDownloadReport = () => {
    // Simulate PDF generation
    console.log('Generating PDF report...');
  };

  const handlePrintReport = () => {
    window.print();
  };

  const handleShareResult = () => {
    if (navigator.share) {
      navigator.share({
        title: 'OpthalmoAI Retinal Screening Result',
        text: `Diabetic Retinopathy Analysis: Stage ${result.stage} detected with ${Math.round(result.confidence * 100)}% confidence`,
      });
    }
  };

  return (
    <div className="space-y-6">
      {/* Medical Disclaimer */}
      <Alert variant="warning" className="bg-amber-50/80 backdrop-blur-sm border-amber-200/50">
        <div className="flex items-start space-x-3">
          <Stethoscope className="h-5 w-5 text-amber-600 flex-shrink-0 mt-0.5" />
          <div>
            <p className="font-medium text-amber-800 mb-1">Important Medical Notice</p>
            <p className="text-amber-700 text-sm">
              These results are generated by AI analysis and are intended to <strong>assist healthcare professionals only</strong>. 
              This is <strong>not a medical diagnosis</strong>. Please consult with an ophthalmologist for proper medical evaluation and treatment decisions.
            </p>
          </div>
        </div>
      </Alert>

      {/* Main Results Card */}
      <Card className="relative overflow-hidden" glow>
        <div className="flex items-start justify-between mb-6">
          <div>
            <h2 className="text-2xl font-bold text-slate-800 mb-2">
              AI Analysis Results
            </h2>
            <p className="text-slate-600">
              Generated on {new Date().toLocaleDateString('en-US', { 
                year: 'numeric', 
                month: 'long', 
                day: 'numeric',
                hour: '2-digit',
                minute: '2-digit'
              })}
            </p>
          </div>
          <Badge variant={getRiskBadgeVariant(result.riskLevel)} className="text-sm px-3 py-1">
            {result.riskLevel.toUpperCase()} RISK
          </Badge>
        </div>

        {/* Stage Information */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6">
          {/* Stage Details */}
          <div className={`p-6 rounded-2xl bg-gradient-to-br from-${stageInfo.color}-50 to-${stageInfo.color}-100 border border-${stageInfo.color}-200`}>
            <div className="flex items-center space-x-4 mb-4">
              <div className={`flex items-center justify-center w-12 h-12 bg-${stageInfo.color}-500 rounded-xl shadow-md`}>
                <IconComponent className="h-7 w-7 text-white" />
              </div>
              <div>
                <h3 className={`text-lg font-bold text-${stageInfo.color}-800`}>
                  Stage {result.stage}
                </h3>
                <p className={`text-${stageInfo.color}-600 font-medium`}>
                  {stageInfo.severity}
                </p>
              </div>
            </div>
            <h4 className={`font-semibold text-${stageInfo.color}-800 mb-2`}>
              {stageInfo.title}
            </h4>
            <p className={`text-${stageInfo.color}-700 text-sm`}>
              {stageInfo.description}
            </p>
          </div>

          {/* Confidence Score */}
          <div className="p-6 rounded-2xl bg-gradient-to-br from-blue-50 to-teal-100 border border-blue-200">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-lg font-bold text-blue-800">
                AI Confidence
              </h3>
              <TrendingUp className="h-6 w-6 text-blue-600" />
            </div>
            <div className="space-y-3">
              <div className="text-3xl font-bold text-blue-800">
                {Math.round(result.confidence * 100)}%
              </div>
              <Progress 
                value={result.confidence * 100} 
                className="h-2" 
              />
              <p className="text-blue-700 text-sm">
                Model confidence in the analysis result
              </p>
            </div>
          </div>
        </div>

        {/* Medical Recommendations */}
        <div className="mb-6">
          <div className="bg-gradient-to-r from-blue-50 to-teal-50 p-6 rounded-2xl border border-blue-200/50">
            <div className="flex items-center mb-5">
              <div className="flex items-center justify-center w-10 h-10 bg-gradient-to-br from-blue-500 to-teal-500 rounded-xl shadow-lg mr-3">
                <Eye className="h-5 w-5 text-white" />
              </div>
              <div>
                <h3 className="text-xl font-bold text-slate-800">Medical Recommendations</h3>
                <p className="text-slate-600 text-sm">Evidence-based guidance for optimal care</p>
              </div>
            </div>
            
            <div className="space-y-3">
              {result.recommendations.map((recommendation, index) => {
                // Parse recommendation for special formatting
                const isUrgent = recommendation.includes('URGENT') || recommendation.includes('EMERGENCY');
                const isImportant = recommendation.includes('⚠️') || recommendation.includes('🚨');
                const isPositive = recommendation.includes('✅') || recommendation.includes('No diabetic retinopathy');
                
                return (
                  <div
                    key={index}
                    className={`group relative overflow-hidden rounded-xl border transition-all duration-200 hover:shadow-md ${
                      isUrgent 
                        ? 'bg-gradient-to-r from-red-50 to-orange-50 border-red-200 hover:border-red-300' 
                        : isImportant
                        ? 'bg-gradient-to-r from-amber-50 to-yellow-50 border-amber-200 hover:border-amber-300'
                        : isPositive
                        ? 'bg-gradient-to-r from-emerald-50 to-green-50 border-emerald-200 hover:border-emerald-300'
                        : 'bg-gradient-to-r from-slate-50 to-blue-50 border-slate-200 hover:border-blue-300'
                    }`}
                  >
                    <div className="flex items-start space-x-4 p-4">
                      {/* Priority Indicator */}
                      <div className={`flex-shrink-0 w-8 h-8 rounded-full flex items-center justify-center shadow-sm ${
                        isUrgent
                          ? 'bg-gradient-to-br from-red-500 to-orange-500'
                          : isImportant 
                          ? 'bg-gradient-to-br from-amber-500 to-yellow-500'
                          : isPositive
                          ? 'bg-gradient-to-br from-emerald-500 to-green-500'
                          : 'bg-gradient-to-br from-blue-500 to-teal-500'
                      }`}>
                        <span className="text-white font-bold text-sm">{index + 1}</span>
                      </div>
                      
                      {/* Recommendation Content */}
                      <div className="flex-1 min-w-0">
                        <p className={`leading-relaxed ${
                          isUrgent
                            ? 'text-red-800 font-medium'
                            : isImportant
                            ? 'text-amber-800 font-medium' 
                            : isPositive
                            ? 'text-emerald-800'
                            : 'text-slate-700'
                        }`}>
                          {recommendation}
                        </p>
                        
                        {/* Priority Badge */}
                        {(isUrgent || isImportant) && (
                          <div className="mt-2">
                            <span className={`inline-flex items-center px-2.5 py-1 rounded-full text-xs font-medium ${
                              isUrgent 
                                ? 'bg-red-100 text-red-800 border border-red-200'
                                : 'bg-amber-100 text-amber-800 border border-amber-200'
                            }`}>
                              {isUrgent ? '🚨 High Priority' : '⚠️ Important'}
                            </span>
                          </div>
                        )}
                        
                        {isPositive && (
                          <div className="mt-2">
                            <span className="inline-flex items-center px-2.5 py-1 rounded-full text-xs font-medium bg-emerald-100 text-emerald-800 border border-emerald-200">
                              ✅ Positive Finding
                            </span>
                          </div>
                        )}
                      </div>
                    </div>
                    
                    {/* Subtle Accent Line */}
                    <div className={`absolute left-0 top-0 w-1 h-full ${
                      isUrgent 
                        ? 'bg-gradient-to-b from-red-500 to-orange-500'
                        : isImportant
                        ? 'bg-gradient-to-b from-amber-500 to-yellow-500'
                        : isPositive
                        ? 'bg-gradient-to-b from-emerald-500 to-green-500'
                        : 'bg-gradient-to-b from-blue-500 to-teal-500'
                    }`}></div>
                  </div>
                );
              })}
            </div>
            
            {/* Medical Disclaimer for Recommendations */}
            <div className="mt-4 p-3 bg-white/60 backdrop-blur-sm rounded-lg border border-blue-200/30">
              <p className="text-xs text-slate-600 flex items-start">
                <Shield className="h-3 w-3 text-blue-500 mr-1 mt-0.5 flex-shrink-0" />
                <span>
                  <strong>Medical Guidance:</strong> These recommendations are AI-generated suggestions based on image analysis. 
                  Always consult with qualified healthcare professionals for personalized medical advice and treatment decisions.
                </span>
              </p>
            </div>
          </div>
        </div>

        {/* Actions */}
        <div className="flex flex-wrap gap-3 pt-6 border-t border-slate-200/50">
          <Button onClick={handleDownloadReport} variant="primary">
            <Download className="h-4 w-4 mr-2" />
            Download Report
          </Button>
          <Button onClick={handlePrintReport} variant="outline">
            <Printer className="h-4 w-4 mr-2" />
            Print Results
          </Button>
          <Button onClick={handleShareResult} variant="outline">
            <Share2 className="h-4 w-4 mr-2" />
            Share
          </Button>
          <Button onClick={onNewAnalysis} variant="ghost">
            <Eye className="h-4 w-4 mr-2" />
            New Analysis
          </Button>
        </div>
      </Card>

      {/* Detailed Information */}
      <Card>
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-lg font-semibold text-slate-800">
            Understanding Your Results
          </h3>
          <Button
            variant="ghost"
            size="sm"
            onClick={() => setShowDetailedInfo(!showDetailedInfo)}
          >
            {showDetailedInfo ? 'Hide Details' : 'Show Details'}
          </Button>
        </div>

        {showDetailedInfo && (
          <div className="space-y-4 pt-4 border-t border-slate-200/50">
            
            {/* Clinical Analysis Details */}
            {(result as any).analysisDetails && (
              <div>
                <h4 className="font-medium text-slate-800 mb-3">Clinical Analysis Details</h4>
                <div className="grid md:grid-cols-2 gap-4 text-sm">
                  
                  {/* Fundus Features */}
                  {(result as any).analysisDetails.fundusFeatures && (
                    <div className="bg-slate-50 p-3 rounded-lg">
                      <h5 className="font-medium text-slate-700 mb-2">Fundus Features</h5>
                      <div className="space-y-1">
                        <div className="flex justify-between">
                          <span>Microaneurysms:</span>
                          <span className="font-medium">{(result as any).analysisDetails.fundusFeatures.microaneurysms}</span>
                        </div>
                        <div className="flex justify-between">
                          <span>Hemorrhages:</span>
                          <span className="font-medium">{(result as any).analysisDetails.fundusFeatures.hemorrhages}</span>
                        </div>
                        <div className="flex justify-between">
                          <span>Hard Exudates:</span>
                          <span className="font-medium">{(result as any).analysisDetails.fundusFeatures.exudates}</span>
                        </div>
                        <div className="flex justify-between">
                          <span>Cotton Wool Spots:</span>
                          <span className="font-medium">{(result as any).analysisDetails.fundusFeatures.cottonWoolSpots}</span>
                        </div>
                        <div className="flex justify-between">
                          <span>Neovascularization:</span>
                          <span className={`font-medium ${(result as any).analysisDetails.fundusFeatures.neovascularization ? 'text-red-600' : 'text-green-600'}`}>
                            {(result as any).analysisDetails.fundusFeatures.neovascularization ? 'Present' : 'Absent'}
                          </span>
                        </div>
                      </div>
                    </div>
                  )}

                  {/* Vessel Analysis */}
                  {(result as any).analysisDetails.vesselsAnalysis && (
                    <div className="bg-slate-50 p-3 rounded-lg">
                      <h5 className="font-medium text-slate-700 mb-2">Vessel Analysis</h5>
                      <div className="space-y-1">
                        <div className="flex justify-between">
                          <span>A/V Ratio:</span>
                          <span className="font-medium">{(result as any).analysisDetails.vesselsAnalysis.arteriovenousRatio}</span>
                        </div>
                        <div className="flex justify-between">
                          <span>Caliber:</span>
                          <span className="font-medium">{(result as any).analysisDetails.vesselsAnalysis.caliber}</span>
                        </div>
                        <div className="flex justify-between">
                          <span>Tortuosity:</span>
                          <span className="font-medium">{(result as any).analysisDetails.vesselsAnalysis.tortuosity}</span>
                        </div>
                      </div>
                    </div>
                  )}

                  {/* Macular Assessment */}
                  {(result as any).analysisDetails.macularAssessment && (
                    <div className="bg-slate-50 p-3 rounded-lg">
                      <h5 className="font-medium text-slate-700 mb-2">Macular Assessment</h5>
                      <div className="space-y-1">
                        <div className="flex justify-between">
                          <span>Macular Edema:</span>
                          <span className={`font-medium ${(result as any).analysisDetails.macularAssessment.edemaPresent ? 'text-red-600' : 'text-green-600'}`}>
                            {(result as any).analysisDetails.macularAssessment.edemaPresent ? 'Present' : 'Absent'}
                          </span>
                        </div>
                        <div className="flex justify-between">
                          <span>Foveal Reflex:</span>
                          <span className="font-medium">{(result as any).analysisDetails.macularAssessment.fovealReflex}</span>
                        </div>
                        <div className="flex justify-between">
                          <span>Central Thickness:</span>
                          <span className="font-medium">{(result as any).analysisDetails.macularAssessment.thickness}μm</span>
                        </div>
                      </div>
                    </div>
                  )}

                  {/* Enhanced Image Quality */}
                  {result.imageQuality && (
                    <div className="bg-slate-50 p-3 rounded-lg">
                      <h5 className="font-medium text-slate-700 mb-2">Image Quality Metrics</h5>
                      <div className="space-y-1">
                        <div className="flex justify-between">
                          <span>Overall Quality:</span>
                          <span className="font-medium">{Math.round(result.imageQuality.qualityScore * 100)}%</span>
                        </div>
                        <div className="flex justify-between">
                          <span>Brightness:</span>
                          <span className="font-medium">{Math.round(result.imageQuality.brightness * 100)}%</span>
                        </div>
                        <div className="flex justify-between">
                          <span>Contrast:</span>
                          <span className="font-medium">{Math.round(result.imageQuality.contrast * 100)}%</span>
                        </div>
                        {(result.imageQuality as any).sharpness && (
                          <div className="flex justify-between">
                            <span>Sharpness:</span>
                            <span className="font-medium">{Math.round((result.imageQuality as any).sharpness * 100)}%</span>
                          </div>
                        )}
                        {(result.imageQuality as any).fieldCoverage && (
                          <div className="flex justify-between">
                            <span>Field Coverage:</span>
                            <span className="font-medium">{Math.round((result.imageQuality as any).fieldCoverage * 100)}%</span>
                          </div>
                        )}
                      </div>
                    </div>
                  )}
                </div>
                
                {/* Clinical Notes */}
                {(result as any).clinicalNotes && (
                  <div className="bg-blue-50 p-3 rounded-lg mt-4">
                    <h5 className="font-medium text-blue-800 mb-2">Clinical Notes</h5>
                    <p className="text-blue-700 text-sm">{(result as any).clinicalNotes}</p>
                  </div>
                )}
              </div>
            )}
            
            <div>
              <h4 className="font-medium text-slate-800 mb-2">Diabetic Retinopathy Stages:</h4>
              <div className="grid gap-3 text-sm">
                <div className="flex items-center space-x-3">
                  <div className="w-3 h-3 bg-emerald-500 rounded-full"></div>
                  <span className="text-slate-700"><strong>Stage 0:</strong> No diabetic retinopathy</span>
                </div>
                <div className="flex items-center space-x-3">
                  <div className="w-3 h-3 bg-blue-500 rounded-full"></div>
                  <span className="text-slate-700"><strong>Stage 1:</strong> Mild nonproliferative diabetic retinopathy</span>
                </div>
                <div className="flex items-center space-x-3">
                  <div className="w-3 h-3 bg-amber-500 rounded-full"></div>
                  <span className="text-slate-700"><strong>Stage 2:</strong> Moderate nonproliferative diabetic retinopathy</span>
                </div>
                <div className="flex items-center space-x-3">
                  <div className="w-3 h-3 bg-orange-500 rounded-full"></div>
                  <span className="text-slate-700"><strong>Stage 3:</strong> Severe nonproliferative diabetic retinopathy</span>
                </div>
                <div className="flex items-center space-x-3">
                  <div className="w-3 h-3 bg-red-500 rounded-full"></div>
                  <span className="text-slate-700"><strong>Stage 4:</strong> Proliferative diabetic retinopathy</span>
                </div>
              </div>
            </div>

            <div className="pt-4 border-t border-slate-200/50">
              <div className="flex items-start space-x-3">
                <Shield className="h-5 w-5 text-teal-600 flex-shrink-0 mt-0.5" />
                <div>
                  <h4 className="font-medium text-slate-800 mb-1">Privacy & Security</h4>
                  <p className="text-slate-600 text-sm">
                    Your retinal images are processed securely and are automatically deleted after analysis. 
                    No personal medical data is stored permanently, ensuring HIPAA compliance and patient privacy.
                  </p>
                </div>
              </div>
            </div>
          </div>
        )}
      </Card>

      {/* Next Steps */}
      <Card className="bg-gradient-to-r from-teal-50 to-blue-50 border-teal-200/50">
        <div className="flex items-start space-x-4">
          <div className="flex items-center justify-center w-12 h-12 bg-teal-500 rounded-xl shadow-md flex-shrink-0">
            <Calendar className="h-6 w-6 text-white" />
          </div>
          <div>
            <h3 className="text-lg font-semibold text-teal-800 mb-2">
              Next Steps
            </h3>
            <p className="text-teal-700 text-sm mb-4">
              Based on your AI screening results, we recommend scheduling an appointment with an ophthalmologist 
              for professional evaluation and to discuss appropriate treatment options if needed.
            </p>
            <Button variant="secondary" size="sm">
              <Stethoscope className="h-4 w-4 mr-2" />
              Find Healthcare Providers
            </Button>
          </div>
        </div>
      </Card>
    </div>
  );
};