import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Card, Button, Badge, Alert } from '../components/ui';
import { dataService } from '../services';
import { 
  ArrowLeft, 
  FileText, 
  Download, 
  Eye, 
  Calendar,
  Clock,
  Search,
  Filter,
  Trash2,
  Plus,
  Archive,
  TrendingUp,
  RefreshCw
} from 'lucide-react';

interface AnalysisReport {
  id: string;
  date: string;
  stage: number;
  confidence: number;
  riskLevel: 'low' | 'moderate' | 'high';
  status: 'completed' | 'pending' | 'archived';
  fileName?: string;
  stageName?: string;
}

const ReportsPage: React.FC = () => {
  const navigate = useNavigate();
  const [reports, setReports] = useState<AnalysisReport[]>([]);
  const [filteredReports, setFilteredReports] = useState<AnalysisReport[]>([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [filterStatus, setFilterStatus] = useState<'all' | 'completed' | 'pending' | 'archived'>('all');
  const [isLoading, setIsLoading] = useState(true);
  const [lastUpdated, setLastUpdated] = useState(new Date());

  const loadReportsData = () => {
    try {
      const screeningResults = dataService.getAllScreenings();
      const analysisReports: AnalysisReport[] = screeningResults.map(screening => ({
        id: screening.id,
        date: screening.timestamp,
        stage: screening.stage,
        confidence: screening.confidence,
        riskLevel: screening.riskLevel as 'low' | 'moderate' | 'high',
        status: 'completed' as const, // All screenings from dataService are completed
        fileName: screening.fileName,
        stageName: screening.stageName
      }));
      
      setReports(analysisReports);
      setFilteredReports(analysisReports);
      setLastUpdated(new Date());
    } catch (error) {
      console.error('Error loading reports:', error);
      setReports([]);
      setFilteredReports([]);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    loadReportsData();

    // Auto-refresh every 30 seconds
    const interval = setInterval(() => {
      loadReportsData();
    }, 30000);

    // Refresh when page becomes visible
    const handleVisibilityChange = () => {
      if (!document.hidden) {
        loadReportsData();
      }
    };

    document.addEventListener('visibilitychange', handleVisibilityChange);

    return () => {
      clearInterval(interval);
      document.removeEventListener('visibilitychange', handleVisibilityChange);
    };
  }, []);

  // Add refresh functionality
  const handleRefresh = () => {
    setIsLoading(true);
    setTimeout(() => loadReportsData(), 500); // Small delay for UX
  };

  useEffect(() => {
    let filtered = reports;

    // Filter by status
    if (filterStatus !== 'all') {
      filtered = filtered.filter(report => report.status === filterStatus);
    }

    // Filter by search term
    if (searchTerm) {
      filtered = filtered.filter(report => 
        report.id.toLowerCase().includes(searchTerm.toLowerCase()) ||
        new Date(report.date).toLocaleDateString().includes(searchTerm) ||
        report.riskLevel.toLowerCase().includes(searchTerm.toLowerCase())
      );
    }

    setFilteredReports(filtered);
  }, [reports, searchTerm, filterStatus]);

  const handleGoBack = () => {
    navigate('/');
  };

  const handleNewAnalysis = () => {
    navigate('/upload');
  };

  const handleViewReport = (reportId: string) => {
    navigate(`/results/${reportId}`);
  };

  const handleDownloadReport = (reportId: string) => {
    const report = reports.find(r => r.id === reportId);
    if (!report) return;

    const reportContent = `
OpthalmoAI Analysis Report
========================

Report ID: ${report.id}
Date: ${new Date(report.date).toLocaleDateString()}
Time: ${new Date(report.date).toLocaleTimeString()}
${report.fileName ? `Image File: ${report.fileName}` : ''}

DIABETIC RETINOPATHY SCREENING RESULTS
=====================================

Stage: ${report.stage}/4 ${report.stageName ? `(${report.stageName})` : ''}
Risk Level: ${report.riskLevel.toUpperCase()}
Confidence Score: ${(report.confidence * 100).toFixed(1)}%
Status: ${report.status.toUpperCase()}

Generated by OpthalmoAI - AI-Powered Retinal Screening Platform
    `;

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `OpthalmoAI_Report_${report.id}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleDeleteReport = (reportId: string) => {
    if (window.confirm('Are you sure you want to delete this report?')) {
      const deleted = dataService.deleteScreeningResult(reportId);
      if (deleted) {
        loadReportsData(); // Refresh the data
      }
    }
  };

  const handleArchiveReport = (reportId: string) => {
    // For now, archiving means deleting since we don't have archive status in dataService
    // In future, we could add archive functionality to dataService
    if (window.confirm('Archive this report? (This will remove it from active reports)')) {
      const deleted = dataService.deleteScreeningResult(reportId);
      if (deleted) {
        loadReportsData(); // Refresh the data
      }
    }
  };

  const getStageInfo = (stage: number) => {
    const stages = [
      { name: 'No DR', color: 'success' },
      { name: 'Mild DR', color: 'info' },
      { name: 'Moderate DR', color: 'warning' },
      { name: 'Severe DR', color: 'danger' },
      { name: 'Proliferative DR', color: 'danger' }
    ];
    return stages[stage] || stages[0];
  };

  const getRiskBadgeVariant = (riskLevel: string) => {
    switch (riskLevel) {
      case 'low': return 'success';
      case 'moderate': return 'warning';
      case 'high': return 'danger';
      default: return 'info';
    }
  };

  const getStatusBadgeVariant = (status: string) => {
    switch (status) {
      case 'completed': return 'success';
      case 'pending': return 'warning';
      case 'archived': return 'info';
      default: return 'info';
    }
  };

  if (isLoading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50/30 to-teal-50/50 py-8">
        <div className="max-w-6xl mx-auto px-4">
          <Card className="p-8 text-center">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-teal-600 mx-auto mb-4"></div>
            <h2 className="text-xl font-semibold text-slate-800 mb-2">Loading Reports</h2>
            <p className="text-slate-600">Retrieving your analysis history...</p>
          </Card>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50/30 to-teal-50/50 py-4 sm:py-8">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="mb-6 sm:mb-8">
          <Button
            variant="ghost"
            onClick={handleGoBack}
            className="mb-4 text-slate-600 hover:text-teal-600"
          >
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to Home
          </Button>
          
          <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between space-y-4 lg:space-y-0">
            <div>
              <div className="flex flex-col sm:flex-row sm:items-center mb-4 space-y-4 sm:space-y-0 sm:space-x-4">
                <div className="flex items-center justify-center w-12 h-12 sm:w-16 sm:h-16 bg-gradient-to-r from-teal-500 to-blue-600 rounded-2xl shadow-lg flex-shrink-0">
                  <FileText className="h-6 w-6 sm:h-8 sm:w-8 text-white" />
                </div>
                <div className="text-center sm:text-left">
                  <h1 className="text-2xl sm:text-3xl lg:text-4xl font-bold bg-gradient-to-r from-teal-600 to-blue-600 bg-clip-text text-transparent">
                    Analysis Reports
                  </h1>
                  <p className="text-slate-600 text-sm sm:text-base lg:text-lg">
                    View and manage your retinal screening history
                  </p>
                  <p className="text-xs text-slate-500 mt-1">
                    Last updated: {lastUpdated.toLocaleTimeString()}
                  </p>
                </div>
              </div>
            </div>
            
            <div className="flex flex-col sm:flex-row gap-2">
              <Button 
                variant="outline" 
                onClick={handleRefresh} 
                disabled={isLoading}
                className="w-full sm:w-auto min-h-[48px]"
              >
                <RefreshCw className={`w-4 h-4 mr-2 ${isLoading ? 'animate-spin' : ''}`} />
                Refresh
              </Button>
              <Button onClick={handleNewAnalysis} className="w-full sm:w-auto min-h-[48px]">
                <Plus className="w-4 h-4 mr-2" />
                New Analysis
              </Button>
            </div>
          </div>
        </div>

        {/* Statistics */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6 sm:mb-8">
          <Card className="p-3 sm:p-4 text-center">
            <div className="text-lg sm:text-2xl font-bold text-teal-600 mb-1">{reports.length}</div>
            <div className="text-xs sm:text-sm text-slate-600">Total Reports</div>
          </Card>
          <Card className="p-3 sm:p-4 text-center">
            <div className="text-lg sm:text-2xl font-bold text-emerald-600 mb-1">
              {reports.filter(r => r.status === 'completed').length}
            </div>
            <div className="text-xs sm:text-sm text-slate-600">Completed</div>
          </Card>
          <Card className="p-3 sm:p-4 text-center">
            <div className="text-lg sm:text-2xl font-bold text-amber-600 mb-1">
              {reports.filter(r => r.riskLevel === 'low').length}
            </div>
            <div className="text-xs sm:text-sm text-slate-600">Low Risk</div>
          </Card>
          <Card className="p-3 sm:p-4 text-center">
            <div className="text-lg sm:text-2xl font-bold text-blue-600 mb-1">
              {reports.length > 0 ? Math.round(reports.reduce((sum, r) => sum + r.confidence, 0) / reports.length * 100) : 0}%
            </div>
            <div className="text-xs sm:text-sm text-slate-600">Avg Confidence</div>
          </Card>
        </div>

        {/* Filters and Search */}
        <Card className="p-4 mb-6">
          <div className="flex flex-col lg:flex-row gap-4 items-stretch lg:items-center">
            <div className="flex-1 min-w-0">
              <div className="relative">
                <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-slate-400 w-4 h-4" />
                <input
                  type="text"
                  placeholder="Search reports by ID, date, or risk level..."
                  className="w-full pl-10 pr-4 py-3 lg:py-2 border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-teal-500 text-sm sm:text-base"
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                />
              </div>
            </div>
            
            <div className="flex items-center space-x-2 flex-shrink-0">
              <Filter className="w-4 h-4 text-slate-600" />
              <select
                className="border border-slate-200 rounded-lg px-3 py-3 lg:py-2 focus:outline-none focus:ring-2 focus:ring-teal-500 min-w-0 flex-1 lg:flex-none text-sm sm:text-base"
                value={filterStatus}
                onChange={(e) => setFilterStatus(e.target.value as any)}
              >
                <option value="all">All Reports</option>
                <option value="completed">Completed</option>
              </select>
            </div>
          </div>
        </Card>

        {/* Reports List */}
        {filteredReports.length === 0 ? (
          <Card className="p-6 sm:p-8 text-center">
            <FileText className="w-12 h-12 sm:w-16 sm:h-16 text-slate-300 mx-auto mb-4" />
            <h3 className="text-lg sm:text-xl font-semibold text-slate-800 mb-2">No Reports Found</h3>
            <p className="text-slate-600 mb-4 text-sm sm:text-base px-4">
              {searchTerm || filterStatus !== 'all' 
                ? 'No reports match your current filters.' 
                : 'No analysis reports found. Upload retinal images to generate reports.'}
            </p>
            <Button onClick={handleNewAnalysis} className="w-full sm:w-auto min-h-[48px]">
              <Plus className="w-4 h-4 mr-2" />
              Start Your First Analysis
            </Button>
          </Card>
        ) : (
          <div className="space-y-4">
            {filteredReports.map((report) => {
              const stageInfo = getStageInfo(report.stage);
              return (
                <Card key={report.id} className="p-4 sm:p-6 hover:shadow-lg transition-shadow">
                  {/* Mobile Layout */}
                  <div className="block lg:hidden space-y-4">
                    <div className="flex items-center justify-between">
                      <div>
                        <div className="font-semibold text-slate-800">Report #{report.id}</div>
                        <div className="text-sm text-slate-600 flex items-center mt-1">
                          <Calendar className="w-3 h-3 mr-1" />
                          {new Date(report.date).toLocaleDateString()}
                        </div>
                        <div className="text-sm text-slate-600 flex items-center">
                          <Clock className="w-3 h-3 mr-1" />
                          {new Date(report.date).toLocaleTimeString()}
                        </div>
                      </div>
                      <Badge variant={getStatusBadgeVariant(report.status) as any}>
                        {report.status}
                      </Badge>
                    </div>
                    
                    <div className="grid grid-cols-3 gap-4 text-center">
                      <div>
                        <div className="font-bold text-slate-800">Stage {report.stage}</div>
                        <Badge variant={stageInfo.color as any} className="text-xs">
                          {stageInfo.name}
                        </Badge>
                      </div>
                      <div>
                        <div className="font-semibold text-teal-600">
                          {(report.confidence * 100).toFixed(1)}%
                        </div>
                        <div className="text-xs text-slate-600">Confidence</div>
                      </div>
                      <div>
                        <Badge variant={getRiskBadgeVariant(report.riskLevel) as any}>
                          {report.riskLevel} Risk
                        </Badge>
                      </div>
                    </div>
                    
                    <div className="grid grid-cols-2 gap-2">
                      <Button
                        size="sm"
                        variant="outline"
                        onClick={() => handleViewReport(report.id)}
                        className="w-full min-h-[40px]"
                      >
                        <Eye className="w-3 h-3 mr-1" />
                        View
                      </Button>
                      <Button
                        size="sm"
                        variant="ghost"
                        onClick={() => handleDownloadReport(report.id)}
                        className="w-full min-h-[40px]"
                      >
                        <Download className="w-3 h-3 mr-1" />
                        Download
                      </Button>
                    </div>
                  </div>

                  {/* Desktop Layout */}
                  <div className="hidden lg:grid lg:grid-cols-6 gap-4 items-center">
                    <div>
                      <div className="font-semibold text-slate-800">Report #{report.id}</div>
                      <div className="text-sm text-slate-600 flex items-center mt-1">
                        <Calendar className="w-3 h-3 mr-1" />
                        {new Date(report.date).toLocaleDateString()}
                      </div>
                      <div className="text-sm text-slate-600 flex items-center">
                        <Clock className="w-3 h-3 mr-1" />
                        {new Date(report.date).toLocaleTimeString()}
                      </div>
                    </div>
                    
                    <div className="text-center">
                      <div className="font-bold text-lg text-slate-800">Stage {report.stage}</div>
                      <Badge variant={stageInfo.color as any} className="text-xs">
                        {stageInfo.name}
                      </Badge>
                    </div>
                    
                    <div className="text-center">
                      <div className="font-semibold text-teal-600">
                        {(report.confidence * 100).toFixed(1)}%
                      </div>
                      <div className="text-xs text-slate-600">Confidence</div>
                    </div>
                    
                    <div className="text-center">
                      <Badge variant={getRiskBadgeVariant(report.riskLevel) as any}>
                        {report.riskLevel} Risk
                      </Badge>
                    </div>
                    
                    <div className="text-center">
                      <Badge variant={getStatusBadgeVariant(report.status) as any}>
                        {report.status}
                      </Badge>
                    </div>
                    
                    <div className="flex items-center justify-end space-x-2">
                      <Button
                        size="sm"
                        variant="outline"
                        onClick={() => handleViewReport(report.id)}
                      >
                        <Eye className="w-3 h-3 mr-1" />
                        View
                      </Button>
                      
                      <Button
                        size="sm"
                        variant="ghost"
                        onClick={() => handleDownloadReport(report.id)}
                      >
                        <Download className="w-3 h-3" />
                      </Button>
                      
                      {report.status === 'completed' && (
                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={() => handleArchiveReport(report.id)}
                        >
                          <Archive className="w-3 h-3" />
                        </Button>
                      )}
                      
                      <Button
                        size="sm"
                        variant="ghost"
                        onClick={() => handleDeleteReport(report.id)}
                        className="text-red-600 hover:text-red-700"
                      >
                        <Trash2 className="w-3 h-3" />
                      </Button>
                    </div>
                  </div>
                </Card>
              );
            })}
          </div>
        )}

        {/* Export All */}
        {filteredReports.length > 0 && (
          <Card className="p-4 mt-6">
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between space-y-4 sm:space-y-0">
              <div className="text-sm text-slate-600">
                Showing {filteredReports.length} of {reports.length} reports
              </div>
              <div className="flex flex-col sm:flex-row space-y-2 sm:space-y-0 sm:space-x-2">
                <Button variant="outline" size="sm" className="w-full sm:w-auto min-h-[40px]">
                  <Download className="w-4 h-4 mr-2" />
                  Export All
                </Button>
                <Button variant="outline" size="sm" className="w-full sm:w-auto min-h-[40px]">
                  <TrendingUp className="w-4 h-4 mr-2" />
                  Analytics
                </Button>
              </div>
            </div>
          </Card>
        )}

        {/* Medical Disclaimer */}
        <div className="mt-8">
          <Alert variant="info">
            <Eye className="w-4 h-4" />
            <div>
              <strong>Report Management:</strong> All analysis reports are stored securely and 
              comply with healthcare privacy standards. Reports should be shared only with 
              authorized healthcare providers. For questions about your results, consult 
              with a qualified eye care professional.
            </div>
          </Alert>
        </div>
      </div>
    </div>
  );
};

export default ReportsPage;