import React, { useState, useEffect } from 'react';
import { useParams, useNavigate, useLocation } from 'react-router-dom';
import { ResultsDisplay } from '../components/ResultsDisplay';
import { Card, Button, Badge, Alert } from '../components/ui';
import { 
  ArrowLeft, 
  Download, 
  Eye, 
  Calendar,
  Clock,
  Shield,
  FileText,
  Printer,
  RefreshCw
} from 'lucide-react';

interface AnalysisResult {
  id: string;
  stage: number;
  confidence: number;
  riskLevel: 'low' | 'moderate' | 'high';
  timestamp: string;
  recommendations: string[];
}

interface ResultsPageState {
  result: AnalysisResult | null;
  file: File | null;
  isLoading: boolean;
  error: string | null;
}

const ResultsPage: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const location = useLocation();
  const [state, setState] = useState<ResultsPageState>({
    result: null,
    file: null,
    isLoading: true,
    error: null
  });

  useEffect(() => {
    // Check if results were passed via navigation state
    if (location.state?.result) {
      setState({
        result: location.state.result,
        file: location.state.file || null,
        isLoading: false,
        error: null
      });
    } else {
      // Simulate loading results by ID
      setTimeout(() => {
        // Mock result for demonstration
        const mockResult: AnalysisResult = {
          id: id || '1',
          stage: 2,
          confidence: 0.89,
          riskLevel: 'moderate',
          timestamp: new Date().toISOString(),
          recommendations: [
            'Follow-up examination recommended within 6 months',
            'Monitor blood glucose levels regularly',
            'Consider consultation with retinal specialist',
            'Maintain optimal diabetes management'
          ]
        };

        setState({
          result: mockResult,
          file: null,
          isLoading: false,
          error: null
        });
      }, 1500);
    }
  }, [id, location.state]);

  const handleGoBack = () => {
    navigate('/');
  };

  const handleNewAnalysis = () => {
    navigate('/analysis');
  };

  const handleDownloadReport = () => {
    if (!state.result) return;

    // Generate and download a mock report
    const reportContent = `
OpthalmoAI Analysis Report
========================

Analysis ID: ${state.result.id}
Date: ${new Date(state.result.timestamp).toLocaleDateString()}
Time: ${new Date(state.result.timestamp).toLocaleTimeString()}

DIABETIC RETINOPATHY SCREENING RESULTS
=====================================

Stage: ${state.result.stage}/4
Risk Level: ${state.result.riskLevel.toUpperCase()}
Confidence Score: ${(state.result.confidence * 100).toFixed(1)}%

RECOMMENDATIONS
===============
${state.result.recommendations.map((rec, index) => `${index + 1}. ${rec}`).join('\n')}

MEDICAL DISCLAIMER
==================
This analysis is generated by an AI screening tool and is intended for assistive purposes only.
Results should be reviewed by a qualified healthcare professional.
This tool does not replace professional medical diagnosis or treatment decisions.

Generated by OpthalmoAI - AI-Powered Retinal Screening Platform
    `;

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `OpthalmoAI_Report_${state.result.id}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  const getStageInfo = (stage: number) => {
    const stages = [
      { name: 'No DR', description: 'No diabetic retinopathy detected', color: 'success' },
      { name: 'Mild DR', description: 'Mild non-proliferative diabetic retinopathy', color: 'info' },
      { name: 'Moderate DR', description: 'Moderate non-proliferative diabetic retinopathy', color: 'warning' },
      { name: 'Severe DR', description: 'Severe non-proliferative diabetic retinopathy', color: 'danger' },
      { name: 'Proliferative DR', description: 'Proliferative diabetic retinopathy', color: 'danger' }
    ];
    return stages[stage] || stages[0];
  };

  if (state.isLoading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50/30 to-teal-50/50 py-8">
        <div className="max-w-4xl mx-auto px-4">
          <Card className="p-8 text-center">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-teal-600 mx-auto mb-4"></div>
            <h2 className="text-xl font-semibold text-slate-800 mb-2">Loading Results</h2>
            <p className="text-slate-600">Retrieving your analysis results...</p>
          </Card>
        </div>
      </div>
    );
  }

  if (state.error || !state.result) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50/30 to-teal-50/50 py-8">
        <div className="max-w-4xl mx-auto px-4">
          <Alert variant="error" className="mb-4">
            <Shield className="w-4 h-4" />
            {state.error || 'Results not found'}
          </Alert>
          <Button onClick={handleGoBack}>Return to Home</Button>
        </div>
      </div>
    );
  }

  const stageInfo = getStageInfo(state.result.stage);

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50/30 to-teal-50/50 py-4 sm:py-8">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="mb-6 sm:mb-8">
          <Button
            variant="ghost"
            onClick={handleGoBack}
            className="mb-4 text-slate-600 hover:text-teal-600"
          >
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to Home
          </Button>
          
          <div className="text-center">
            <div className="flex items-center justify-center mb-4">
              <div className="flex items-center justify-center w-12 h-12 sm:w-16 sm:h-16 bg-gradient-to-r from-teal-500 to-blue-600 rounded-2xl shadow-lg">
                <Eye className="h-6 w-6 sm:h-8 sm:w-8 text-white" />
              </div>
            </div>
            <h1 className="text-2xl sm:text-3xl lg:text-4xl font-bold bg-gradient-to-r from-teal-600 to-blue-600 bg-clip-text text-transparent mb-2">
              Analysis Results
            </h1>
            <p className="text-slate-600 text-sm sm:text-base lg:text-lg px-4">
              Complete diabetic retinopathy screening report
            </p>
          </div>
        </div>

        {/* Results Summary */}
        <Card className="p-4 sm:p-6 mb-6" glow>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 sm:gap-6 mb-4 sm:mb-6">
            <div className="text-center">
              <div className="text-2xl sm:text-3xl font-bold text-slate-800 mb-1">
                Stage {state.result.stage}
              </div>
              <Badge variant={stageInfo.color as any} className="mb-2">
                {stageInfo.name}
              </Badge>
              <p className="text-xs sm:text-sm text-slate-600 px-2">{stageInfo.description}</p>
            </div>
            
            <div className="text-center">
              <div className="text-2xl sm:text-3xl font-bold text-teal-600 mb-1">
                {(state.result.confidence * 100).toFixed(1)}%
              </div>
              <p className="text-xs sm:text-sm text-slate-600 mb-2">Confidence Score</p>
              <Badge variant="info">High Accuracy</Badge>
            </div>
            
            <div className="text-center">
              <div className="text-lg font-semibold text-slate-800 mb-1 capitalize">
                {state.result.riskLevel} Risk
              </div>
              <div className="flex items-center justify-center text-xs sm:text-sm text-slate-600 mb-2">
                <Calendar className="w-4 h-4 mr-1" />
                {new Date(state.result.timestamp).toLocaleDateString()}
              </div>
              <div className="flex items-center justify-center text-xs sm:text-sm text-slate-600">
                <Clock className="w-4 h-4 mr-1" />
                {new Date(state.result.timestamp).toLocaleTimeString()}
              </div>
            </div>
          </div>
        </Card>

        {/* Detailed Results */}
        <ResultsDisplay result={state.result} onNewAnalysis={handleNewAnalysis} />

        {/* Action Buttons */}
        <div className="mt-6 sm:mt-8 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">
          <Button onClick={handleDownloadReport} variant="outline" className="w-full min-h-[48px]">
            <Download className="w-4 h-4 mr-2" />
            Download Report
          </Button>
          
          <Button onClick={handlePrint} variant="outline" className="w-full min-h-[48px]">
            <Printer className="w-4 h-4 mr-2" />
            Print Results
          </Button>
          
          <Button onClick={() => navigate('/reports')} variant="outline" className="w-full min-h-[48px]">
            <FileText className="w-4 h-4 mr-2" />
            View All Reports
          </Button>
          
          <Button onClick={handleNewAnalysis} className="w-full min-h-[48px]">
            <RefreshCw className="w-4 h-4 mr-2" />
            New Analysis
          </Button>
        </div>

        {/* Medical Disclaimer */}
        <div className="mt-8">
          <Alert variant="warning">
            <Shield className="w-4 h-4" />
            <div>
              <strong>Important Medical Disclaimer:</strong> This AI analysis is intended as a screening 
              tool to assist healthcare professionals and should not be used as the sole basis for 
              medical decisions. All results should be reviewed and interpreted by a qualified 
              eye care professional or physician. This tool does not replace comprehensive eye 
              examinations or professional medical diagnosis.
            </div>
          </Alert>
        </div>
      </div>
    </div>
  );
};

export default ResultsPage;